---
# Playbook
# provision.yml
# Provision servers using the linode v4 api
- name: Deploy development server infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ./group_vars/main.yml
    - ./group_vars/secrets.yml

  tasks:

    - name: Create a Linode instance
      community.general.linode_v4:
        access_token: "{{ api_token }}"
        root_pass: "{{ password }}"
        label: "{{ item.name }}"
        type: g6-nanode-1
        region: "{{ linode_region }}"
        image: "{{ linode_image }}"
        private_ip: false
        authorized_keys:
          - "{{ local_home }}/{{ ssh_key_dir }}/{{ ssh_key_name }}.pub"  # this installs the pub key on remote server
        state: present
      loop: "{{ linode_servers }}"
      register: linode_results

    - name: Set dynamic inventory file header
      copy:
        dest: "{{ dynamic_inventory_file }}"
        content: |
          [linode_nodes]
      when: linode_results is defined

    - name: Add each Linode node to the dynamic inventory file
      lineinfile:
        path: "{{ dynamic_inventory_file }}"
        line: |
          {{ item.instance.label }} ansible_host={{ item.instance.ipv4[0] }} ansible_user={{ setup_user }} ansible_private_key_file="{{ local_home }}/{{ ssh_key_dir }}/{{ ssh_key_name }}"
      loop: "{{ linode_results.results }}"
      when: linode_results is defined

    - name: Display generated dynamic inventory
      debug:
        msg: |
          Inventory generated at: {{ dynamic_inventory_file }}
          ---
          {{ lookup('file', dynamic_inventory_file) }}

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      ansible.builtin.wait_for:
        host: "{{ item.instance.ipv4[0] }}"
        port: 22
        search_regex: OpenSSH
        delay: 10
        timeout: 300
        state: started
      loop: "{{ linode_results.results }}"
