# setup linodes after they've been provisioned
- name: Configure linode instances
  hosts: linode_nodes
  any_errors_fatal: true
  gather_facts: true
  user: "{{ setup_user }}"

  vars:
    local_home: "{{ lookup('env','HOME') }}"

  vars_files:
    - ./group_vars/main.yml
    - ./group_vars/secrets.yml

  roles:
    - role: common
    - role: devtools
    - role: shell
    - role: summary
