# setup linodes after they've been provisioned
- name: Configure linode instances
  hosts: all
  any_errors_fatal: true
  user: root
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  vars_files:
    - ./group_vars/main.yml
    - ./group_vars/secrets.yml

  roles:
    - role: common
    - role: devtools
